name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
      REMOTE_PATH: ${{ vars.REMOTE_PATH }}
      AWS_SSH_ACCESS: ${{ secrets.SSH_KEY_AWS }}
      LOCAL_PATH: ${{ vars.LOCAL_PATH }}
    
    steps:
          - name: Checkout
            uses: actions/checkout@v3
            
          - id: validation
            name: Validation acess-key from ssh
            run: |
              ls -ilha
              echo "${AWS_SSH_ACCESS}" > $SECRET_PATH
              
          - name: Check permissions
            run: |
              chmod 400 $SECRET_PATH            
              
          - name: Update code
            run: |
              cd $LOCAL_PATH && rm -rf .*
              scp -i $SECRET_PATH -o "StrictHostKeyChecking no" -r $LOCAL_PATH/* $REMOTE_PATH
              echo "Finish"
