name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
      REMOTE_PATH: ${{ vars.REMOTE_PATH }}
      AWS_SSH_ACCESS: ${{ secrets.SSH_KEY_AWS }}"
    
    steps:
          - id: validation
            name: Validation acess-key from ssh
            run: |
              echo "My REMOTE_PATH is $REMOTE_PATH"
              echo "My secret path is $SECRET_PATH"
              echo "SSH Key: $AWS_SSH_ACCESS"
              
          - name: Check permissions
            run: |
              chmod 400 /tmp/server.pem
              cat /tmp/server.pem
              ls -ilha /tmp/server.pem
              
              
          - name: Update code
            run: |
              scp -i $SECRET_PATH -o "StrictHostKeyChecking no" -r . $REMOTE_PATH
              echo "Finish"
