name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
          - id: validation
            name: Validation acess-key from ssh
            run: |
              echo "${{ vars.APP_ID }}"
              echo "Github Repo: ${GITHUB_REPOSITORY}"
              echo "SSH Key: ${{ secrets.SSH_KEY_AWS }}"
              
          - name: Check permissions
            run: |
              chmod 400 /tmp/server.pem
              cat /tmp/server.pem
              ls -ilha /tmp/server.pem
              
              
          - name: Update code
            run: |
              scp -i /tmp/server.pem -o "StrictHostKeyChecking no" -r . admin@18.134.95.111:/var/www/html/
              echo "Finish"
