name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
      REMOTE_PATH: ${{ vars.REMOTE_PATH }}
      AWS_SSH_ACCESS: ${{ secrets.SSH_KEY_AWS }}
    
    steps:
          - name: Checkout
            uses: actions/checkout@v3
            
          - id: validation
            name: Validation acess-key from ssh
            run: |
              echo "${AWS_SSH_ACCESS}" > $SECRET_PATH
              
          - name: Check permissions
            run: |
              chmod 400 $SECRET_PATH  
              
          - name: Clean env
            run: ${{ secrets.CLEAN_ENV }}
              
          - name: Update code
            run: |
              rm -rf .git .github
              scp -i $SECRET_PATH -o "StrictHostKeyChecking no" -r $(pwd)/* $REMOTE_PATH
              echo "Finish"
