name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
      REMOTE_PATH: ${{ vars.REMOTE_PATH }}
      AWS_SSH_ACCESS: ${{ secrets.SSH_KEY_AWS }}
    
    steps:
          - id: validation
            name: Validation acess-key from ssh
            run: |
              echo "${AWS_SSH_ACCESS}" > $SECRET_PATH
              
          - name: Check permissions
            run: |
              chmod 400 $SECRET_PATH            
              
          - name: Update code
            run: |
              pwd && ls /home/runner/work/vuln_appsec/ && ls /home/runner/work/vuln_appsec/vuln_appsec/
              scp -i $SECRET_PATH -o "StrictHostKeyChecking no" -r . $REMOTE_PATH
              echo "Finish"
