name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  CONTAINER_NAME: MY_CONTAINER_NAME

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
          - id: validation
            name: Validation acess-key from ssh
            run: |
              pwd
              ls
              echo ${{secrets.SSH_KEY_AWS}} > /tmp/server.pem
              chmod 400 /tmp/server.pem
              cat /tmp/server.pem
              
          - name: Update code
            run: |
              pwd
              scp -i /tmp/server.pem -o "StrictHostKeyChecking no" -r . admin@18.134.95.111:/var/www/html/
              echo "Finish"
